remote_theme: pmarsceill/just-the-docs

logo: "assets/images/ExchangeLabOpsImage.png"

# # Aux links for the upper right navigation
# aux_links:
#   "<img src='assets/images/ExchangeLabOpsImage.png' alt='BC Gov'/>":
#     - "//github.com/pmarsceill/just-the-docs"

footer_content: "<a href='gov.bc.ca'><img src='/ExchangeLabOps/assets/images/BCID_H_rgb_pos.png' height='42' width='200' class='center' alt='BC Gov'/> </a>"

