remote_theme: pmarsceill/just-the-docs

logo: "/assets/images/BCDevExchange-avatar.png"

footer_content: '''
<style> 
footer-body {
  background-color: #036;
}
</style>
<div class="footer-body>
  <p> Footer content </p>
</div>
'''
