remote_theme: pmarsceill/just-the-docs

logo: "assets/images/ExchangeLabOpsImage.png"

# # Aux links for the upper right navigation
# aux_links:
#   "<img src='assets/images/ExchangeLabOpsImage.png' alt='BC Gov'/>":
#     - "//github.com/pmarsceill/just-the-docs"

footer_content: "<img src='/ExchangeLabOps/assets/images/ExchangeLabOpsImage.png' height='42' alt='BC Gov'/>"

